

name = "portfolio-react"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
pages_build_output_dir = "dist"

[[send_email]]
name = "CONTACT_EMAIL"
destination_address = "jarno.mommens@gmail.com"

[vars]
CONTACT_FROM = "no-reply@your-domain.com"
CONTACT_TO = "jarno.mommens@gmail.com"